name: alfariz_property
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  
  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1

  # Product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/logo_light_mode.png
  color_dark: "#000000"
  image_dark: assets/logos/logo_dark_mode.png
  android: true
  ios: false
  web: false
  android_12:
    image: assets/logos/logo_light_mode.png
    image_dark: assets/logos/logo_dark_mode.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"

flutter_icons:
  android: true
  ios: {}
  web: {}
  macos: {}
  image_path: "assets/logos/logo_light_mode.png"


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        # - asset: assets/fonts/Poppins-Regular.ttf
